localhost:8080/employee/add?firstName=Ivan&lastName=Ivanov&salary=1000&departmentId=1
###
localhost:8080/employee/add?firstName=Petr&lastName=Ivanov&salary=2000&departmentId=1
###
localhost:8080/employee/add?firstName=Semen&lastName=Ivanov&salary=3000&departmentId=2
###
localhost:8080/employee/add?firstName=Sergey&lastName=Ivanov&salary=4000&departmentId=2

###
localhost:8080/department/1/employees
###
localhost:8080/department/1/salary/sum
###
localhost:8080/department/1/salary/max
###
localhost:8080/department/1/salary/min
###
localhost:8080/department/employees